#!/usr/bin/env bash
# 将 infra/migrations 按编号顺序合并输出，供「新建 Supabase 项目」在 SQL Editor 一次粘贴执行。
# 用法（仓库根目录）：
#   A) 更新仓库内给 SQL Editor 用的文件（改迁移后记得重跑）：
#        bash scripts/print-supabase-migrations.sh > infra/migrations/ALL_FOR_SQL_EDITOR.sql
#      再在 IDE 打开 ALL_FOR_SQL_EDITOR.sql，全选复制 → Supabase SQL Editor → Run
#   B) 临时文件：bash scripts/print-supabase-migrations.sh > /tmp/rsa_migrations.sql

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

FILES=(
  infra/migrations/001_insight_tasks.sql
  infra/migrations/002_reviews.sql
  infra/migrations/003_review_analysis.sql
  infra/migrations/004_insight_tasks_dictionary_vertical.sql
  infra/migrations/005_platform_users.sql
  infra/migrations/006_insight_tasks_created_by.sql
)

echo "-- RSA infra migrations bundle (empty project)"
echo "-- Generated by scripts/print-supabase-migrations.sh"
echo ""

for f in "${FILES[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "missing: $f" >&2
    exit 1
  fi
  echo "-- >>> $f"
  cat "$f"
  echo ""
done

echo "-- done"
