#!/usr/bin/env bash
# 将 infra/migrations 按编号顺序合并输出，供「新建 Supabase 项目」在 SQL Editor 一次粘贴执行。
# 用法（仓库根目录）：
#   A) 更新仓库内给 SQL Editor 用的文件（改迁移后记得重跑）：
#        bash scripts/sql-bundle.sh > infra/migrations/ALL_FOR_SQL_EDITOR.sql
#      再在 IDE 打开 ALL_FOR_SQL_EDITOR.sql，全选复制 → Supabase SQL Editor → Run
#   B) 临时文件：bash scripts/sql-bundle.sh > /tmp/rsa_migrations.sql

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

FILES=(
  infra/migrations/001_insight_tasks.sql
  infra/migrations/002_reviews.sql
  infra/migrations/003_review_analysis.sql
  infra/migrations/004_insight_tasks_dictionary_vertical.sql
  infra/migrations/005_platform_users.sql
  infra/migrations/006_insight_tasks_created_by.sql
  infra/migrations/008_insight_tasks_product_snapshot.sql
  infra/migrations/009_audit_logs.sql
  infra/migrations/010_dictionary_review_queue.sql
  infra/migrations/011_taxonomy_entries.sql
  infra/migrations/012_review_dimension_unmatched.sql
  infra/migrations/013_review_analysis_dimension_status.sql
  infra/migrations/014_sentiment_temp_tables.sql
  infra/migrations/015_sentiment_unmatched_pools.sql
  infra/migrations/016_topic_discovery_pools.sql
  infra/migrations/017_topic_discovery_jobs.sql
  infra/migrations/018_topic_discovery_jobs_global.sql
  infra/migrations/019_taxonomy_entries_excel_import_defaults.sql
  infra/migrations/020_insight_tasks_ai_summary.sql
  infra/migrations/021_dictionary_review_queue_rejected_kind.sql
)

echo "-- RSA infra migrations bundle (empty project)"
echo "-- Generated by scripts/sql-bundle.sh"
echo ""

for f in "${FILES[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "missing: $f" >&2
    exit 1
  fi
  echo "-- >>> $f"
  cat "$f"
  echo ""
done

echo "-- done"
