-- RSA infra migrations bundle (empty project)
-- Generated by scripts/print-supabase-migrations.sh

-- >>> infra/migrations/001_insight_tasks.sql
-- 评论洞察任务表（与 docs/plan 中 insight_tasks 概念对齐）
-- 在 Supabase SQL Editor 中执行，或通过迁移工具应用

CREATE TABLE IF NOT EXISTS public.insight_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  platform TEXT NOT NULL,
  product_id TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'success', 'failed', 'cancelled')),
  analysis_provider_id TEXT,
  error_code TEXT,
  error_message TEXT,
  failure_stage TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_insight_tasks_status_created
  ON public.insight_tasks (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_insight_tasks_product
  ON public.insight_tasks (platform, product_id);

ALTER TABLE public.insight_tasks ENABLE ROW LEVEL SECURITY;

-- 服务密钥（后端 FastAPI）会绕过 RLS；若需 anon 读表请另行写 policy。
COMMENT ON TABLE public.insight_tasks IS 'Insight pipeline tasks; backend uses service role';

-- >>> infra/migrations/002_reviews.sql
-- 评论原文（TB-2）：与 insight_tasks 关联，供后续分析与证据追溯

CREATE TABLE IF NOT EXISTS public.reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  insight_task_id UUID NOT NULL REFERENCES public.insight_tasks (id) ON DELETE CASCADE,
  platform TEXT NOT NULL,
  product_id TEXT NOT NULL,
  external_review_id TEXT,
  raw_text TEXT NOT NULL,
  title TEXT,
  rating REAL,
  sku TEXT,
  reviewed_at TIMESTAMPTZ,
  lang TEXT,
  extra JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_reviews_task_created
  ON public.reviews (insight_task_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_reviews_product
  ON public.reviews (platform, product_id);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.reviews IS 'Raw reviews from configured fetch API; service role writes';

-- >>> infra/migrations/003_review_analysis.sql
-- TB-4：评论级分析结果 + 六维命中行（可按任务/商品/维度检索；review_id 反查 reviews.raw_text）

CREATE TABLE IF NOT EXISTS public.review_analysis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  insight_task_id UUID NOT NULL REFERENCES public.insight_tasks (id) ON DELETE CASCADE,
  review_id UUID NOT NULL REFERENCES public.reviews (id) ON DELETE CASCADE,
  platform TEXT NOT NULL,
  product_id TEXT NOT NULL,
  sentiment_label TEXT NOT NULL CHECK (sentiment_label IN ('negative', 'neutral', 'positive')),
  sentiment_confidence REAL,
  analysis_provider_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (insight_task_id, review_id)
);

CREATE INDEX IF NOT EXISTS idx_review_analysis_task ON public.review_analysis (insight_task_id);
CREATE INDEX IF NOT EXISTS idx_review_analysis_product ON public.review_analysis (platform, product_id);
CREATE INDEX IF NOT EXISTS idx_review_analysis_review ON public.review_analysis (review_id);

CREATE TABLE IF NOT EXISTS public.review_dimension_analysis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  review_analysis_id UUID NOT NULL REFERENCES public.review_analysis (id) ON DELETE CASCADE,
  insight_task_id UUID NOT NULL REFERENCES public.insight_tasks (id) ON DELETE CASCADE,
  review_id UUID NOT NULL REFERENCES public.reviews (id) ON DELETE CASCADE,
  platform TEXT NOT NULL,
  product_id TEXT NOT NULL,
  dimension TEXT NOT NULL CHECK (
    dimension IN (
      'pros',
      'cons',
      'return_reasons',
      'purchase_motivation',
      'user_expectation',
      'usage_scenario'
    )
  ),
  keywords TEXT[] NOT NULL DEFAULT '{}',
  evidence_quote TEXT,
  highlight_spans JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rda_task ON public.review_dimension_analysis (insight_task_id);
CREATE INDEX IF NOT EXISTS idx_rda_product_dim ON public.review_dimension_analysis (platform, product_id, dimension);
CREATE INDEX IF NOT EXISTS idx_rda_review ON public.review_dimension_analysis (review_id);

ALTER TABLE public.review_analysis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_dimension_analysis ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.review_analysis IS 'Per-review sentiment snapshot for an insight task (TB-4)';
COMMENT ON TABLE public.review_dimension_analysis IS 'Six-dimension hits with evidence; join reviews via review_id (TB-4)';

-- >>> infra/migrations/004_insight_tasks_dictionary_vertical.sql
-- 洞察任务绑定词典垂直（类目）：general 兜底，electronics 等一级垂直可叠加专用词条

ALTER TABLE public.insight_tasks
  ADD COLUMN IF NOT EXISTS dictionary_vertical_id TEXT NOT NULL DEFAULT 'general';

COMMENT ON COLUMN public.insight_tasks.dictionary_vertical_id IS
  '词典类目：general=通用兜底，electronics=电子产品等；分析请求会随任务传给分析服务';

CREATE INDEX IF NOT EXISTS idx_insight_tasks_dictionary_vertical
  ON public.insight_tasks (dictionary_vertical_id);

-- >>> infra/migrations/005_platform_users.sql
-- 平台用户（登录与菜单权限）；后端使用 service role 访问

CREATE TABLE IF NOT EXISTS public.platform_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  menu_keys JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_platform_users_status ON public.platform_users (status);

ALTER TABLE public.platform_users ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.platform_users IS 'Platform login users; menu_keys JSON array of menu keys; backend only';

-- 默认管理员 admin / admin（bcrypt）；首次部署后请修改密码
INSERT INTO public.platform_users (username, password_hash, status, menu_keys)
VALUES (
  'admin',
  '$2b$12$ogCVFZuYrlHwt7RAPTEkeeIEafK2Op96WwPTddzJ9AY3Q94L9kUTG',
  'active',
  '["insight","compare","pain-audit","dictionary","api-config","audit-log","account-permissions"]'::jsonb
)
ON CONFLICT (username) DO NOTHING;

-- >>> infra/migrations/006_insight_tasks_created_by.sql
-- 洞察任务创建人（登录用户名，由前端 X-RSA-Username 传入）

ALTER TABLE public.insight_tasks
  ADD COLUMN IF NOT EXISTS created_by TEXT;

COMMENT ON COLUMN public.insight_tasks.created_by IS
  '创建人用户名（与 platform_users.username 对齐；历史数据可为空）';

CREATE INDEX IF NOT EXISTS idx_insight_tasks_created_by ON public.insight_tasks (created_by);

-- >>> infra/migrations/007_compare_runs.sql
-- 对比分析记录（服务端持久化，替代浏览器 localStorage）

CREATE TABLE IF NOT EXISTS public.compare_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  platform_a TEXT NOT NULL,
  product_id_a TEXT NOT NULL,
  platform_b TEXT NOT NULL,
  product_id_b TEXT NOT NULL,
  creator TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  model_id TEXT,
  model_label TEXT,
  status TEXT NOT NULL CHECK (status IN ('success', 'failed')),
  error_message TEXT,
  result JSONB
);

CREATE INDEX IF NOT EXISTS idx_compare_runs_created_at ON public.compare_runs (created_at DESC);

ALTER TABLE public.compare_runs ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.compare_runs IS 'Product compare runs; FastAPI uses service role (bypasses RLS)';

-- >>> infra/migrations/008_insight_tasks_product_snapshot.sql
-- 商品快照（Pangolin amzProductDetail 等）：标题、主图、展示价，供列表展示
ALTER TABLE public.insight_tasks
  ADD COLUMN IF NOT EXISTS product_snapshot JSONB;

COMMENT ON COLUMN public.insight_tasks.product_snapshot IS
  'Product metadata snapshot (title, image_url, price_display); written on fetch-reviews when provider supplies it';

-- >>> infra/migrations/009_audit_logs.sql
-- 操作审计日志（账号、菜单、摘要信息；detail 存结构化补充）
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT NOT NULL DEFAULT '',
  menu_key TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  detail JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs (created_at DESC);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.audit_logs IS 'Operation audit trail; FastAPI inserts via service role';

-- done
